CREATE DATABASE testing;

CREATE EXTENSION cube;

create table if not exists vec128x1krows ( id serial primary key, value cube);
create table if not exists vec128x5krows ( id serial primary key, value cube);
create table if not exists vec128x10krows ( id serial primary key, value cube);
create table if not exists vec128x25krows ( id serial primary key, value cube);
create table if not exists vec128x50krows ( id serial primary key, value cube);
create table if not exists vec128x100krows ( id serial primary key, value cube);
create table if not exists vec128x500krows ( id serial primary key, value cube);
create table if not exists vec128x1000krows ( id serial primary key, value cube);
create table if not exists vec256x1krows ( id serial primary key, value cube);
create table if not exists vec256x5krows ( id serial primary key, value cube);
create table if not exists vec256x10krows ( id serial primary key, value cube);
create table if not exists vec256x25krows ( id serial primary key, value cube);
create table if not exists vec256x50krows ( id serial primary key, value cube);
create table if not exists vec256x100krows ( id serial primary key, value cube);
create table if not exists vec256x500krows ( id serial primary key, value cube);
create table if not exists vec256x1000krows ( id serial primary key, value cube);
create table if not exists vec512x1krows ( id serial primary key, value cube);
create table if not exists vec512x5krows ( id serial primary key, value cube);
create table if not exists vec512x10krows ( id serial primary key, value cube);
create table if not exists vec512x25krows ( id serial primary key, value cube);
create table if not exists vec512x50krows ( id serial primary key, value cube);
create table if not exists vec512x100krows ( id serial primary key, value cube);
create table if not exists vec512x500krows ( id serial primary key, value cube);
create table if not exists vec512x1000krows ( id serial primary key, value cube);

CREATE VIEW cube128 AS
	SELECT cube (
		ARRAY[
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random())
		]);

-- cube 256
CREATE VIEW cube256 AS
	SELECT cube (
		ARRAY[
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random())
		]);

-- cube 512
CREATE VIEW cube512 AS
	SELECT cube (
		ARRAY[
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random()),
			(select random())
		     ]
	);

do $$
	begin
		for i in 1..25000 loop
			INSERT INTO vec128x25krows (value) VALUES ((select * from cube128));
			INSERT INTO vec256x25krows (value) VALUES ((select * from cube256));
			INSERT INTO vec512x25krows (value) VALUES ((select * from cube512));
		end loop;
	end;
$$;

do $$
	begin
		for i in 1..500000 loop
			INSERT INTO vec128x500krows (value) VALUES ((select * from cube128));
			INSERT INTO vec256x500krows (value) VALUES ((select * from cube256));
			INSERT INTO vec512x500krows (value) VALUES ((select * from cube512));
		end loop;
	end;
$$;

do $$
	begin
		for i in 1..50000 loop
			INSERT INTO vec128x50krows (value) VALUES ((select * from cube128));
			INSERT INTO vec256x50krows (value) VALUES ((select * from cube256));
			INSERT INTO vec512x50krows (value) VALUES ((select * from cube512));
		end loop;
	end;
$$;

do $$
	begin
		for i in 1..5000 loop
			INSERT INTO vec128x5krows (value) VALUES ((select * from cube128));
			INSERT INTO vec256x5krows (value) VALUES ((select * from cube256));
			INSERT INTO vec512x5krows (value) VALUES ((select * from cube512));
		end loop;
	end;
$$;

do $$
	begin
		for i in 1..1000 loop
			INSERT INTO vec128x1krows (value) VALUES ((select * from cube128));
			INSERT INTO vec256x1krows (value) VALUES ((select * from cube256));
			INSERT INTO vec512x1krows (value) VALUES ((select * from cube512));
		end loop;
	end;
$$;

do $$
	begin
		for i in 1..10000 loop
			INSERT INTO vec128x10krows (value) VALUES ((select * from cube128));
			INSERT INTO vec256x10krows (value) VALUES ((select * from cube256));
			INSERT INTO vec512x10krows (value) VALUES ((select * from cube512));
		end loop;
	end;
$$;

do $$
	begin
		for i in 1..100000 loop
			INSERT INTO vec128x100krows (value) VALUES ((select * from cube128));
			INSERT INTO vec256x100krows (value) VALUES ((select * from cube256));
			INSERT INTO vec512x100krows (value) VALUES ((select * from cube512));
		end loop;
	end;
$$;

do $$
	begin
		for i in 1..1000000 loop
			INSERT INTO vec128x1000krows (value) VALUES ((select * from cube128));
			INSERT INTO vec256x1000krows (value) VALUES ((select * from cube256));
			INSERT INTO vec512x1000krows (value) VALUES ((select * from cube512));
		end loop;
	end;
$$;
